### ISSUE TITLE
'Toggle Code Wrap' and 'Copy Code Snippet' conflict by themselves and with 'Collapse In Comment'

### ISSUE THREAD

**Issue by darkred** [Mottie/GitHub-userscripts#35]
STR

- Using TM 4.5.5663beta in Firefox 58 or TM 4.5 in Chrome 63:
install latest versions of:
'GitHub Collapse In Comment' 1.0.13 
'GitHub Toggle Code Wrap' 1.1.3
'GitHub Copy Code Snippet' 0.1.0

- here is a long code example:

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublime_linter.py", line 263, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1008, in lint_view
    callback(cls.get_view(vid), linters, hit_time)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublime_linter.py", line 316, in highlight
    highlights.draw(other_view)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\highlight.py", line 133, in draw
    all.draw(view)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\highlight.py", line 477, in draw
    icon = self.get_style("icon", style, error_type)
  File "C:\Users\Kostas\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\highlight.py", line 184, in wrapper
    return persist.gutter_marks["icons"][error_type]
KeyError: 'warning'
 
SublimeLinter: -------------------- 
```

- Here is how the markdown is displayed, i.e. the code is not collapsed:
![2018-01-23_180240](https://user-images.githubusercontent.com/723651/35286365-82c1f316-0068-11e8-97ef-fde99e7fe0f7.jpg)
- Clicking the header:
![2018-01-23_181209](https://user-images.githubusercontent.com/723651/35286650-3f9530f2-0069-11e8-9dc7-15be9f07ebf5.jpg)
- Disabling either 'GitHub Toggle Code Wrap' or 'GitHub Copy Code Snippet' or both fixes the issue:
![2018-01-23_180307](https://user-images.githubusercontent.com/723651/35286391-938b235c-0068-11e8-9dc6-df138df7b6ca.jpg)

--- 

Additionally, the two scripts 'GitHub Toggle Code Wrap' and 'GitHub Copy Code Snippet'
work ok by themselves, but their icon is displayed on top of one another.
and so, in order to be able to use them, you have to have only one enabled at a time.

**Comment by Mottie** [comment]
Hi @darkred!

Thanks for letting me know! Hmm, actually they behave differently depending on the priority; though either way, they misbehave! I'll see what I can do later tonight.

**Comment by darkred** [comment]
Thank you for fixing the conflict of ''GitHub Copy Code Snippet'.
Also, the icons of the two scripts no longer overlap.

I see that you closed the issue, but in your commit, no changes for ''GitHub Toggle Code Wrap' were included, but it also conflicts with with 'GitHub Collapse In Comment', i.e. the code block doesn't collapse.
If there's nothing more you can do to make them compatible, ok.
I just wanted to report it to you in case it missed your attention.

**Comment by Mottie** [comment]
Oops, I forgot about the Toggle code wrap code.

**Comment by Mottie** [comment]
All fixed! Please make sure to update both scripts.

**Comment by darkred** [comment]
Thank you!
